- hosts: all
  pre_tasks:
  - name: Kali Upgrade
    become: true
    apt:
      update_cache: yes
      upgrade: yes
      autoremove: yes
      autoclean: yes
    tags:
      - install
      - core
- import_playbook: tasks/kali.yml
- import_playbook: tasks/core.yml
- import_playbook: tasks/fish.yml
- import_playbook: tasks/git.yml
- import_playbook: tasks/repo.yml

