---
- name: Install APT
  hosts: all
  become: false
  vars:
    ppa_list:
      - ppa:neovim-ppa/stable
      - ppa:ethereum/ethereum
      - ppa:fish-shell/release-3
      - ppa:zanchey/asciinema
    apt_packages:
      - libxext-dev
      - fish
      - openjdk-17-jdk
      - ruby-rubygems
      - python3.10-venv
  tasks:
    - name: Install PPA
      become: true
      loop: "{{ ppa_list }}"
      ansible.builtin.apt_repository:
        repo: "{{item}}"
        state: present
    - name: Install Apt Packages
      become: true
      ansible.builtin.package:
        name: "{{ apt_packages }}"
        state: latest
