---
- name: Install Arch
  hosts: localhost
  become: false
  tasks:
    - name: Install the latest version of packages
      become: true
      ansible.builtin.package:
        name:
          - bat
          - cmake
          - exa
          - fish
          - fisher
          - fzf
          - gcc
          - github-cli
          - git
          - go
          - jq
          - lazygit
          - lua-language-server
          - luarocks
          - mpv
          - neovim
          - npm
          - nodejs
          - jdk11-openjdk
          - protobuf
          - ripgrep
          - shellcheck
          - stow
          - stylua
          - tmux
        state: latest
    - name: "Adding dvorak to /etc/vconsole.conf"
      become: true
      ansible.builtin.lineinfile:
        line: KEYMAP=dvorak
        path: /etc/vconsole.conf
        state: present
        search_string: KEYMAP=dvorak
