---
- name: Install Arch
  hosts: all
  become: false
  tasks:
    - name: Install the latest version of packages
      become: true
      ansible.builtin.package:
        name:
          - bc
          - cmake
          - discord
          - fish
          - fisher
          - fzf
          - gcc
          - git
          - github-cli
          - go
          - imagemagick
          - jdk11-openjdk
          - jq
          - lazygit
          - linux-headers
          - luarocks
          - mpv
          - neovim
          - nodejs
          - npm
          - pacman-contrib
          - pamixer
          - pipewire-pulse
          - protobuf
          - rubygems
          - rustup
          - signal-desktop
          - solidity
          - stylua
          - vivaldi
          - which
          - xorg-xinput
        state: latest
    - name: "Adding dvorak to /etc/vconsole.conf"
      become: true
      ansible.builtin.lineinfile:
        line: KEYMAP=dvorak
        path: /etc/vconsole.conf
        state: present
        search_string: KEYMAP=dvorak
