---
- name: Install Arch
  hosts: all
  become: false
  tasks:
    - name: Install the latest version of packages
      become: true
      ansible.builtin.package:
        name:
          - bc
          - cmake
          - discord
          - fish
          - fisher
          - fzf
          - gcc
          - git
          - github-cli
          - go
          - howdy
          - imagemagick
          - jdk11-openjdk
          - jq
          - lazygit
          - linux-headers
          - luarocks
          - mpv
          - neovim
          - nodejs
          - npm
          - pacman-contrib
          - pamixer
          - pipewire-pulse
          - protobuf
          - rubygems
          - rustup
          - signal-desktop
          - solidity
          - stylua
          - telegram-desktop
          - v4l-utils
          - vivaldi
          - which
          - xorg-xinput
          - zbar

          # https://github.com/lutris/docs/blob/master/InstallingDrivers.md#arch--manjaro--other-arch-linux-derivatives
          # https://github.com/lutris/docs/blob/master/WineDependencies.md#archantergosmanjaroother-arch-derivatives
          - steam
          - lutris
        state: latest
    # - name: Installing flatpaks
    #   community.general.flatpak:
    #     name: "{{ flatpak_packages }}"
    #     state: present
    - name: "Adding dvorak to /etc/vconsole.conf"
      become: true
      ansible.builtin.lineinfile:
        line: KEYMAP=dvorak
        path: /etc/vconsole.conf
        state: present
        search_string: KEYMAP=dvorak
