---
- name: Install Arch
  hosts: all
  become: false
  tasks:
    - name: Install the latest version of packages
      become: true
      ansible.builtin.package:
        name:
          - bc
          - cmake
          - discord
          - fish
          - fisher
          - fzf
          - gcc
          - git
          - github-cli
          - go
            # - howdy
          - ffmpegthumbnailer
          - fontpreview
          - imagemagick
          - jdk17-openjdk
          - jq
          - lazygit
          - linux-headers
          - luarocks
          - mpv
          - nodejs
          - npm
          - pacman-contrib
          - pamixer
          - pipewire-pulse
          - poppler
          - protobuf
          - python-pip
          - python-setuptools
          - rubygems
          - rustup
          - signal-desktop
          - solidity
          - stylua
          - telegram-desktop
          - v4l-utils
          - vivaldi
          - which
          - xorg-xinput
          - zbar

          # https://github.com/lutris/docs/blob/master/InstallingDrivers.md#arch--manjaro--other-arch-linux-derivatives
          # https://github.com/lutris/docs/blob/master/WineDependencies.md#archantergosmanjaroother-arch-derivatives
          # - steam
          # - lutris
        state: latest
