---
- name: Install Arch
  hosts: all
  become: false
  tasks:
    - name: Install the latest version of packages
      become: true
      ansible.builtin.package:
        name:
          - aws-cli-v2
          - bc
          - cmake
          - fish
          - fisher
          - fzf
          - gcc
          - git
          - github-cli
          - go
          - ffmpegthumbnailer
          - imagemagick
          - jdk17-openjdk
          - jq
          - lazygit
          - linux-headers
          - luarocks
          - mpv
          - nodejs
          - npm
          - pacman-contrib
          - poppler
          - protobuf
          - python-pip
          - python-pipx
          - python-setuptools
          - rubygems
          - stylua
          - v4l-utils
          - which
          - zbar

          # https://github.com/lutris/docs/blob/master/InstallingDrivers.md#arch--manjaro--other-arch-linux-derivatives
          # https://github.com/lutris/docs/blob/master/WineDependencies.md#archantergosmanjaroother-arch-derivatives
          # - steam
          # - lutris
        state: latest
