---
- name: Install Core
  hosts: localhost
  become: false
  vars:
    brew_packages:
      - bat
      - cheat
      - exa
      - fish
      - fisher
      - fzf
      - gcc
      - gh
      - git
      - gitui
      - go
      - hadolint
      - lua-language-server
      - luarocks
      - neovim
      - node@16
      - openjdk@11
      - protobuf
      - protobuf
      - ripgrep
      - shellcheck
      - stylua
      - tmux
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: true
    go_install_packages:
      - github.com/google/wire/cmd/wire@latest
      - google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - mvdan.cc/sh/v3/cmd/shfmt@latest
    lua_packages:
      - luacheck
    npm_packages:
      - npm
      - neovim
      - bash-language-server
      - vscode-langservers-extracted
      - graphql-language-service-cli
      - solidity-language-server
      - typescript-language-server
    pip_packages:
      - pynvim
      - pyright

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew_check
    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is Missing... set install_homebrew_if_missing to True or Install
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing
    - name:
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

  tasks:
    - name: Updating Homebrew
      community.general.homebrew:
        update_homebrew: yes
      when:
        - homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      community.general.homebrew:
        name: "{{ brew_packages }}"
        upgrade_all: yes
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing go packages
      loop: "{{ go_install_packages }}"
      ansible.builtin.shell:
        cmd: go install {{item|quote}}

    - name: Installing luarocks packages
      loop: "{{ lua_packages }}"
      ansible.builtin.shell:
        cmd: luarocks install {{item|quote}}

    - name: Installing npm packages
      loop: "{{ npm_packages }}"
      community.general.npm:
        name: "{{item|quote}}"
        state: latest
        global: yes
    - name: Installing pip packages
      loop: "{{ pip_packages }}"
      ansible.builtin.pip:
        name: "{{item|quote}}"
        state: latest
