---
- name: Install Core
  hosts: localhost
  become: false
  vars:
    brew_packages:
      - bat
      - cheat
      - cmake
      - exa
      - fish
      - fisher
      - fzf
      - gcc
      - gh
      - git
      - gitui
      - go
      - hadolint
      - lazygit
      - lua-language-server
      - luarocks
      - mpv
      - neovim
      - node@16
      - openjdk@11
      - protobuf
      - ripgrep
      - shellcheck
      - stow
      - stylua
      - tmux
    brew_taps:
      - ethereum/ethereum
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: true
    go_install_packages:
      - github.com/google/wire/cmd/wire@latest
      - golang.org/x/tools/gopls@latest
      - google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - mvdan.cc/sh/v3/cmd/shfmt@latest
    lua_packages:
      - luacheck
    npm_packages:
      - npm
      - neovim
      - bash-language-server
      - vscode-langservers-extracted
      - graphql-language-service-cli
      - solidity-language-server
      - typescript-language-server
    pip_packages:
      - pynvim
      - pyright
      - protontricks

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew_check
    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is Missing... set install_homebrew_if_missing to True or Install
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing
    - name:
      shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing
    - name: NVChad
      ansible.builtin.git:
        depth: 1
        repo: https://github.com/NvChad/NvChad
        dest: ~/.config/nvim

  tasks:
    - name: Upgrading Homebrew Packages
      community.general.homebrew:
        name: "{{ brew_packages }}"
        update_homebrew: yes
        upgrade_all: yes

    - name: "Add fish shell to /etc/shells"
      become: true
      ansible.builtin.lineinfile:
        line: /home/linuxbrew/.linuxbrew/bin/fish
        path: /etc/shells
        state: present
        search_string: /home/linuxbrew/.linuxbrew/bin/fish

    - name: Installing go packages
      loop: "{{ go_install_packages }}"
      ansible.builtin.shell:
        cmd: go install {{item|quote}}

    - name: Installing luarocks packages
      loop: "{{ lua_packages }}"
      ansible.builtin.shell:
        cmd: luarocks install {{item|quote}}

    - name: Installing npm packages
      loop: "{{ npm_packages }}"
      community.general.npm:
        name: "{{item|quote}}"
        state: latest
        global: yes
    - name: Installing pip packages
      loop: "{{ pip_packages }}"
      ansible.builtin.pip:
        name: "{{item|quote}}"
        state: latest
