---
- name: Install Core
  hosts: all
  become: false
  vars:
    core_packages:
      - bat
      - cmake
      - cmatrix
      - exa
      - fzf
      - gcc
      - git
      - github-cli
      - go
      - gopls
      - jq
      - lazygit
      - luarocks
      - lua
      - neovim
      - nodejs
      - protobuf
      - ripgrep
      - shellcheck
      - stow
      - tmux
      - wget
      - which
    go_install_packages:
      - github.com/google/wire/cmd/wire@latest
      - google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - mvdan.cc/gofumpt@latest
      - mvdan.cc/sh/v3/cmd/shfmt@latest
      - honnef.co/go/tools/cmd/staticcheck@latest
    lua_packages:
      - luacheck
    npm_packages:
      - npm
      - neovim
      - eslint_d
      - bash-language-server
      - vscode-langservers-extracted
      - graphql-language-service-cli
      - solidity-language-server
      - typescript-language-server
    pip_packages:
      - protontricks
      - pynvim
      - pyright
      - semgrep

  pre_tasks:
    - name: Tmux Plugin Manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
    - name: AstroNvim
      ansible.builtin.git:
        repo: https://github.com/AstroNvim/AstroNvim.git
        dest: ~/.config/nvim
    - name: Dotfiles
      ansible.builtin.git:
        repo: https://github.com/jayp0521/dotfiles.git
        dest: ~/dotfiles
        track_submodules: true

  tasks:
    - name: Install Core Packages
      become: true
      ansible.builtin.package:
        name: "{{ core_packages }}"
        state: latest
    - name: Download WT tool 
      become: true
      get_url:
        url: https://github.com/yankeexe/git-worktree-switcher/releases/download/0.1.0/wt
        dest: /usr/local/bin/wt
        mode: "0755"

    - name: Installing go packages
      loop: "{{ go_install_packages }}"
      ansible.builtin.shell:
        cmd: go install {{item|quote}}

    - name: Installing luarocks packages
      become: true
      loop: "{{ lua_packages }}"
      ansible.builtin.shell:
        cmd: luarocks install {{item|quote}}

    - name: Installing npm packages
      become: true
      loop: "{{ npm_packages }}"
      community.general.npm:
        name: "{{item|quote}}"
        state: latest
        global: yes
    - name: Installing pip packages
      become: true
      loop: "{{ pip_packages }}"
      ansible.builtin.pip:
        name: "{{item|quote}}"
        state: latest

