---
- name: Install Core
  hosts: all
  become: false
  vars:
    core_packages:
      - bat
      - cargo
      - cmake
      - cmatrix
      - exa
      - fzf
      - gcc
      - git
      - gopls
      - htop
      - jq
      - luarocks
      - mlocate
      - neovim
      - nodejs
      - ripgrep
      - shellcheck
      - stow
      - tmux
      - wget
    cargo_packages:
      - stylua
      - tree-sitter-cli
    go_install_packages:
      - github.com/google/wire/cmd/wire@latest
      - github.com/jesseduffield/lazygit@latest
      - google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - honnef.co/go/tools/cmd/staticcheck@latest
      - mvdan.cc/gofumpt@latest
      - mvdan.cc/sh/v3/cmd/shfmt@latest
      - github.com/josharian/impl@latest
    lua_packages:
      - luacheck
    npm_packages:
      - npm
      - neovim
      - eslint_d
      - bash-language-server
      - vscode-langservers-extracted
      - graphql-language-service-cli
      - solidity-language-server
      - typescript-language-server
    pip_packages:
      - protontricks
      - pynvim
      - pyright
      - pywal
      - ueberzug
      - virtualenv
    gem_packages:
      - tmuxinator

  pre_tasks:
    - name: Tmux Plugin Manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
    - name: AstroNvim
      ansible.builtin.git:
        repo: https://github.com/AstroNvim/AstroNvim.git
        dest: ~/.config/nvim

  tasks:
    - name: Install Core Packages
      become: true
      ansible.builtin.package:
        name: "{{ core_packages }}"
        state: latest
    - name: Download WT tool 
      become: true
      get_url:
        url: https://github.com/yankeexe/git-worktree-switcher/releases/download/0.1.0/wt
        dest: /usr/local/bin/wt
        mode: "0755"

    - name: Installing go packages
      loop: "{{ go_install_packages }}"
      ansible.builtin.shell:
        cmd: go install {{item|quote}}
    - name: Installing cargo packages
      become: true
      community.general.cargo:
        name: "{{cargo_packages}}"
        path: /usr/local
        state: latest

    - name: Installing luarocks packages
      become: true
      loop: "{{ lua_packages }}"
      ansible.builtin.shell:
        cmd: luarocks install {{item|quote}}

    - name: Installing npm packages
      become: true
      loop: "{{ npm_packages }}"
      community.general.npm:
        name: "{{item|quote}}"
        state: latest
        global: yes
    - name: Installing pip packages
      become: true
      loop: "{{ pip_packages }}"
      ansible.builtin.pip:
        name: "{{item|quote}}"
        state: latest
    - name: Installing gem packages
      loop: "{{ gem_packages }}"
      community.general.gem:
        name: "{{item|quote}}"
        state: latest
        include_doc: yes

    # Font Logic
    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory
    - name: Hack exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Caskaydia*Cove*Nerd*Font*"
      register: hack_exists
      ignore_errors: yes
    - name: Download Hack
      when: hack_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

