---
- name: Install Fish Plugins
  hosts: localhost
  become: false
  vars:
    fisher_plugins:
      - jorgebucaran/fisher
      - andreiborisov/sponge
      - catppuccin/fish
      - edc/bass
      - IlanCosman/tide@v5
      - jethrokuan/z
      - jhillyerd/plugin-git
      - PatrickF1/fzf.fish
    fisher_dependencies:
      - fish
  pre_tasks:
    - name: "Ensure fish is in PATH"
      package:
        name: "{{ item }}"
        state: present
      check_mode: true
      loop: "{{ fisher_dependencies }}"
      register: package_check
    - name: "Fish packages"
      debug:
        msg: "Fish dependencies are installed"
      when: package_check is succeeded
  tasks:
    - name: "Install Fisher Plugins"
      loop: "{{ fisher_plugins }}"
      ansible.builtin.shell:
        cmd: fisher install {{item|quote}}
      args:
        executable: /home/linuxbrew/.linuxbrew/bin/fish
