---
- name: Install Fish Plugins
  hosts: all
  become: false
  vars:
    fisher_plugins:
      - jorgebucaran/fisher
      - andreiborisov/sponge
      - catppuccin/fish
      - edc/bass
      - IlanCosman/tide@v5
      - jethrokuan/z
      - jhillyerd/plugin-git
      - PatrickF1/fzf.fish
    fisher_dependencies:
      - fish
  pre_tasks:
    - name: "Ensure fish is in PATH"
      package:
        name: "{{ item }}"
        state: present
      check_mode: true
      loop: "{{ fisher_dependencies }}"
      register: package_check
    - name: "Fish packages"
      debug:
        msg: "Fish dependencies are installed"
      when: package_check is succeeded
  tasks:
    - name: Download fisher
      args:
        executable: /bin/fish
      ansible.builtin.shell:
        cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
    - name: "Install Fisher Plugins"
      loop: "{{ fisher_plugins }}"
      args:
        executable: /bin/fish
      ansible.builtin.shell:
        cmd: fisher install {{item|quote}}
    - name: Create a Directory fish/conf.d
      become: yes
      file:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/fish/conf.d"
        state: directory
        mode: 0755
    - name: Download TokyoNight Fish
      get_url:
        url: https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/fish/tokyonight_storm.fish
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/fish/conf.d"
        force: true
        mode: 0755
