---
- name: Setup Git
  hosts: localhost
  become: false

  tasks:
    - name: Configure Email
      community.general.git_config:
        name: user.email
        scope: global
        value: "36803168+jayp0521@users.noreply.github.com"
    - name: Configure Name
      community.general.git_config:
        name: user.name
        scope: global
        value: "Jay Patel"
    - name: Configure Submodule Recurse
      community.general.git_config:
        name: submodule.recurse
        scope: global
        value: "true"
    - name: Git Clone Coding Packages
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        track_submodules: true
        bare: true
      with_items:
        - { repo: "https://github.com/Architech-App/PlateModel.git", dest: "~/code/PlateModel" }
        - { repo: "https://github.com/Architech-App/PlateAPI.git", dest: "~/code/PlateAPI" }
        - { repo: "https://github.com/Architech-App/PlateWeb.git", dest: "~/code/PlateWeb" }
        
