---
- name: Setup Git
  hosts: localhost
  become: false
  
  tasks:
    - name: Configure Email
      community.general.git_config:
        name: user.email
        scope: global
        value: "36803168+jayp0521@users.noreply.github.com"
    - name: Configure Name
      community.general.git_config:
        name: user.name
        scope: global
        value: "Jay Patel"

