---
- name: Setup Git
  hosts: all
  become: false

  tasks:
    - name: Configure Name
      community.general.git_config:
        name: user.name
        scope: global
        value: "Jay Patel"
    - name: Configure Submodule Recurse
      community.general.git_config:
        name: submodule.recurse
        scope: global
        value: "true"
        
