---
- name: Install Core
  hosts: all
  become: false
  vars:
    brew_packages:
      - bat
      - cheat
      - cmake
      - exa
      - fish
      - fisher
      - fzf
      - gcc
      - gh
      - git
      - gitui
      - go
      - jq
      - hadolint
      - lazygit
      - lua-language-server
      - luarocks
      - mpv
      - neovim
      - node@16
      - openjdk@11
      - protobuf
      - ripgrep
      - shellcheck
      - stow
      - stylua
      - tmux
    brew_taps:
      - ethereum/ethereum
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: true
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew_check
    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is Missing... set install_homebrew_if_missing to True or Install
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing
    - name:
      shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing
    - name: "Adding brew to /etc/environment"
      become: true
      ansible.builtin.lineinfile:
        line: PATH="$PATH:/home/linuxbrew/.linuxbrew/bin/brew"
        path: /etc/environment
        state: present
        search_string: PATH="$PATH:/home/linuxbrew/.linuxbrew/bin/brew"
  tasks:
    - name: Upgrading Homebrew Packages
      community.general.homebrew:
        name: "{{ brew_packages }}"
        update_homebrew: yes
        upgrade_all: yes
    - name: "Add fish shell to /etc/shells"
      become: true
      ansible.builtin.lineinfile:
        line: /home/linuxbrew/.linuxbrew/bin/fish
        path: /etc/shells
        state: present
        search_string: /home/linuxbrew/.linuxbrew/bin/fish

