---
- name: Setup Code Repos
  hosts: all
  become: false

  tasks:
    - name: Configure Email
      community.general.git_config:
        name: user.email
        scope: global
        value: "36803168+jayp0521@users.noreply.github.com"
    - name: Git Clone Coding Packages
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        track_submodules: true
        bare: true
      with_items:
        - { repo: "https://github.com/Architech-App/PlateModel.git", dest: "~/code/PlateModel" }
        - { repo: "https://github.com/Architech-App/PlateAPI.git", dest: "~/code/PlateAPI" }
        - { repo: "https://github.com/Architech-App/PlateWeb.git", dest: "~/code/PlateWeb" }
    - name: Git Clone Coding Packages
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        track_submodules: true
      with_items:
        - { repo: "https://github.com/jayp0521/dotfiles.git", dest: "~/dotfiles" }
        - { repo: "https://github.com/dgileadi/vscode-java-decompiler.git", dest: "~/.local/share/vscode-java-decompiler"}

