---
- name: Setup Code Repos
  hosts: all
  become: false

  tasks:
    - name: Configure Email
      community.general.git_config:
        name: user.email
        scope: global
        value: "36803168+jay-babu@users.noreply.github.com"
    - name: Git Clone Coding Packages
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        track_submodules: true
      with_items:
        - { repo: "https://github.com/jay-babu/dotfiles.git", dest: "~/dotfiles" }
        - { repo: "https://github.com/jay-babu/polybar-scripts.git", dest: "~/.config/polybar/polybar-scripts"}
        - { repo: "https://github.com/dgileadi/vscode-java-decompiler.git", dest: "~/.local/share/vscode-java-decompiler"}
