---
- name: Install Core
  hosts: all
  become: true
  vars:
    xdebs:
      - { link: "https://downloads.vivaldi.com/stable/vivaldi-stable_5.1.2567.66-1_amd64.deb", name: "vivaldi-stable-5.1.2567.66_1"}

  tasks:
    - name: Install xbps packages
      ansible.builtin.package:
        name:
          - fish-shell
          - openjdk11
          - lua-devel
          - mpv
        state: latest
    # - name: Install xdebs
    #   ansible.builtin.shell:
    #     cmd: wget "{{item.link}}" -O "/tmp/{{item.name}}.deb" && /home/void/ansible/submodules/xdeb/xdeb -Sde "/tmp/{{item.name}}.deb" && xbps-install -yR /home/void/.config/xdeb/binpkgs "{{item.name}}"
    #   loop: "{{xdebs}}"
    #   args:
    #     chdir: /home/void/.config/xdeb

